refactored the necessary checks to other files, as well as their tests
GiPHouse/giphouse-website-spring2023 pull request #48
Opened 2023-05-03 13:41 UTC by mitchellboes

Closes #41

### One-sentence description
Refactored `check_members_in_correct_iteration` and `check_double_iteration_names` to their own file, as well as their tests.

### Description
I have not created folders for the AWS files and AWS test files. I would like to, but as we have not decided on a naming scheme we should do that at a later time to avoid merging headaches with other branches that might have different names.

I have quickly changed the pipeline function and its tests to keep the tests from failing. This will be changed later anyways, but I couldn't cope with the red cross on my screen when linting and testing. I also think the removal of checks that are not needed anymore should be handled by the person who refactors the pipeline functionality, as everything will break if I start removing checks without changing the pipeline (which I was not supposed to do, as discussed last meeting).

2023-05-06 11:17 UTC, hb140502 requested changes
Looks good, I have a few comments:
- awssync_checks.py line 9: pipline should be pipeline.
- test_awssync_checks.py: I think the comments are a bit unnecessary, maybe they can be replaced by giving more descriptive names to the aws trees (e.g. aws_tree3 becomes double_iteration_tree).
- test_awssync.py: I think assertRaises(Exception, ...) is a bit too general, because this assert is true even if the exception is raised from the wrong place. This could be fixed by making custom exception classes for each different exception, but I am not sure if that is the best way to do it.

2023-05-06 11:42 UTC, flam123 commented on website/projects/awssync_checks.py
> +        doubles = []
Maybe use a less general name for OU with the same name instead of doubles? duplicates, repeats

2023-05-06 11:51 UTC, flam123 commented on website/projects/awssync_checks.py
> +        incorrect_emails = []
I think this array should be called different, in this test we check if the semester tag of the member matches with the iteration it is in. This naming suggest that there are incorrect emails. Maybe use like inconsistent_tags as name.

2023-05-06 11:53 UTC, flam123 requested changes
See previous comments, must of the changes are really in naming

2023-05-09 09:38 UTC, flam123 approved these changes
Looks good!

2023-05-09 09:38 UTC, hb140502 approved these changes

2023-05-09 09:39 UTC, merged